---

name: "Validate PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title:
    runs-on: ubuntu-20.04
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: "Check PR title"
        # https://github.com/amannn/action-semantic-pull-request
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            fix
            feat
            docs
            ci
            chore
            refactor
            revert
          requireScope: false
          wip: true
          validateSingleCommit: false
